// image-queries.js
// ═══════════════════════════════════════════════════════════════
// GieesK Recipes — curated photo search queries
// ───────────────────────────────────────────────────────────────
// Why this file exists.
//
// fetch-recipe-images.js searches Pexels for "<title> <cuisine> food"
// and takes photos[0] unconditionally. For well-known dishes that is
// fine. For most of the 256 recipes that currently have no photo it is
// not: Pexels has nothing for "Lakotokoto Ugandan food" or "Ombangulu
// Ugandan food" or "Muqmad Geel Somali food", so it returns an
// unrelated food photo and the script writes it in as that dish.
//
// A confidently wrong photo on a recipe page is worse than no photo. It
// tells the reader this is what the dish looks like, and for a
// collection whose whole claim is that it does not invent things, that
// is the same error as inventing a quantity.
//
// So every recipe without a photo gets one of two things here:
//
//   a QUERY  — a phrase that should return a photo which honestly shows
//              this dish, or honestly shows the thing that is actually
//              on the plate. "Posho" queries ugali, because posho IS
//              ugali. "Roasted Simsim" queries roasted sesame seeds,
//              because that is literally what it is.
//
//   null     — no stock photo can honestly represent this dish, so it
//              gets none and the card falls back to its emoji. Each one
//              carries the reason. This is most of the insect dishes,
//              the ash preparations, the ritual vessels, and the
//              regional composites that no generic photo matches.
//
// Queries deliberately avoid the dish's local name where that name
// returns nothing, and describe the visible form instead. They are a
// starting point, not gospel — run with --dry-run first, and use
// review-images.html afterwards to catch the ones that came back wrong.
// ═══════════════════════════════════════════════════════════════

/* Each entry: id: 'query'   or   id: [null, 'why not'] */

const QUERIES = {

  // ─── SOMALIA ────────────────────────────────────────────────
  SOM021: 'ground spice blend bowl',
  SOM022: 'ugali with beef stew',
  SOM023: 'ful medames fava beans',
  SOM024: 'sorghum porridge milk bowl',
  SOM025: 'coconut candy squares',
  SOM026: 'semolina flatbread',
  SOM027: 'fried fish steaks turmeric',
  SOM028: 'fried fish caramelised onions',
  SOM029: 'poached fish broth onion',
  SOM030: 'tomato sauce bowl',
  SOM031: 'semolina cake syrup cream',
  SOM032: 'potato wrapped boiled egg fried',
  SOM033: 'spiced basmati rice',
  SOM034: 'lamb biryani saffron rice',
  SOM035: 'chicken biryani',
  SOM036: 'fried potatoes raisins peppers',
  SOM037: 'rice with vermicelli',
  SOM038: 'spaghetti meat sauce',
  SOM039: 'goat stew tomato potato',
  SOM040: 'lamb bone broth soup',
  SOM041: 'liver and onions pan',
  SOM042: 'grilled liver skewers charcoal',
  SOM043: 'grilled lamb chunks charcoal',
  SOM044: 'fermented flatbread pancake',
  SOM045: 'beef stew plantain',
  SOM046: 'fried plantain slices',
  SOM047: 'okra tomato stew',
  SOM048: 'vegetable stew pot',
  SOM049: 'banana halwa dessert',
  SOM050: 'honeycomb pancake',
  SOM051: 'creme caramel flan',
  SOM052: 'mahamri fried dough',
  SOM053: 'diced chicken potato stir fry',
  SOM054: 'roast whole chicken',
  SOM055: 'buttermilk drink glass',
  SOM056: 'basbousa semolina cake',
  SOM057: [null, 'A decorated ceremonial vessel packed with spiced dried meat, made by a bride\'s mother. No stock photo exists and none can stand in — the object is the dish.'],
  SOM058: 'sesame brittle candy',
  SOM059: 'peanut brittle balls',
  SOM060: 'fried dough syrup balls',
  SOM061: 'roasted coffee beans bowl',
  SOM062: 'seared thin beef steak',
  SOM063: 'pan seared chicken breast',
  SOM064: 'breaded chicken cutlet',
  SOM065: 'pound cake slice',
  SOM066: 'sponge cake slice',
  SOM067: 'lemonade glass ice',
  SOM068: [null, 'Rice on one half of an oval plate and spaghetti on the other, stew over both. The specific arrangement is the dish; a photo of rice or of pasta misrepresents it.'],
  SOM069: 'cardamom coffee cup',
  SOM070: 'spiced tea glass cardamom',
  SOM071: 'avocado milkshake glass',
  SOM072: 'mango milkshake glass',
  SOM073: 'ghee clarified butter jar',
  SOM074: [null, 'Sun-dried camel meat cut to tiny cubes and packed under ghee. Not photographed anywhere, and no dried beef photo honestly shows it.'],
  SOM075: 'fish coconut curry',
  SOM076: 'grilled whole fish turmeric',
  SOM077: 'beef kebab skewers grill',
  SOM078: 'baked eggs vegetables skillet',
  SOM079: 'scrambled eggs vegetables pan',
  SOM080: 'green salad romaine tomato',
  SOM081: 'chickpea bean salad',
  SOM082: 'red bean stew bowl',
  SOM083: 'chicken stew potato carrot',
  SOM084: 'mashed vegetables spinach',
  SOM085: 'piped coconut biscuits',
  SOM086: 'soft bread rolls',

  // ─── SOUTH AFRICA ───────────────────────────────────────────
  ZAF001: 'samp and beans',
  ZAF002: 'crumbly maize meal porridge',
  ZAF003: 'pumpkin porridge bowl',
  ZAF004: 'maize meal with greens',
  ZAF005: 'steamed bread loaf',
  ZAF006: 'sugar beans stew',
  ZAF007: 'cooked trotters stew',
  ZAF008: 'fried liver onions',
  ZAF009: 'crumbly maize pap',
  ZAF010: 'steamed bread dumpling',
  ZAF011: 'pumpkin porridge maize',
  ZAF012: 'samp beans meat bones',
  ZAF013: 'fried chicken gizzards',
  ZAF014: 'soured milk jug',
  ZAF015: 'african sorghum beer',
  ZAF016: 'mopane worms',
  ZAF017: 'bobotie',
  ZAF018: 'dark lamb stew',
  ZAF019: 'koesister cape malay',
  ZAF020: 'chicken biryani pot',
  ZAF021: 'tripe curry',
  ZAF022: 'lamb tomato stew',
  ZAF023: 'pickled fish cape malay',
  ZAF024: 'sosaties lamb apricot skewers',
  ZAF025: 'melktert milk tart',
  ZAF026: 'koeksisters',
  ZAF027: 'malva pudding',
  ZAF028: 'coconut jam tart squares',
  ZAF029: 'peppermint crisp tart',
  ZAF030: 'south african rusks',
  ZAF031: 'vetkoek fried dough',
  ZAF032: 'roosterkoek braai bread',
  ZAF033: 'grilled cheese sandwich braai',
  ZAF034: 'potjiekos cast iron pot',
  ZAF035: 'bunny chow curry bread',
  ZAF036: 'durban fish curry',
  ZAF037: 'dhal curry lentils',
  ZAF038: 'samosas fried triangles',
  ZAF039: 'maize flatbread roti',
  ZAF040: 'layered roti flatbread',
  ZAF041: 'chakalaka relish',
  ZAF042: 'kota quarter loaf sandwich',
  ZAF043: [null, 'A halved sheep\'s head. Pexels will return either nothing or something grim and unrelated; this one is better left to a photograph you take or license deliberately.'],
  ZAF044: [null, 'A Sunday plate defined by having seven distinctly coloured things arranged around a centre. No single stock photo is that plate.'],
  ZAF045: 'peri peri chilli sauce',
  ZAF046: 'grilled peri peri chicken',
  ZAF047: 'beef stew red wine garlic',
  ZAF048: 'steak roll sandwich',
  ZAF049: 'smoked fish potato onion pan',
  ZAF050: [null, 'Defined by waterblommetjies, Cape pondweed flower spikes. A generic mutton stew photo hides the one ingredient the dish is named for.'],
  ZAF051: 'smoked fish pate',
  ZAF052: [null, 'Chopped liver wrapped in squares of caul fat and grilled. Nothing generic resembles it.'],
  ZAF053: 'pounded shredded beef',
  ZAF054: 'sorghum grain bowl',
  ZAF055: 'sour sorghum porridge',
  ZAF056: 'samp peanuts bowl',
  ZAF057: 'samp beans peanuts',
  ZAF058: 'cowpea leaves peanut stew',
  ZAF059: 'dried leafy greens cooked',
  ZAF060: 'biltong dried beef',
  ZAF061: 'droewors dried sausage',
  ZAF062: 'boerewors sausage coil',
  ZAF063: 'milk porridge cinnamon',
  ZAF064: 'pumpkin fritters',
  ZAF065: 'mashed green beans potato',
  ZAF066: 'tripe stew',
  ZAF067: 'grilled chicken feet',
  ZAF068: 'gatsby sandwich',
  ZAF069: 'grilled whole fish braai',
  ZAF070: 'boerewors coil braai grill',

  // ─── UGANDA ─────────────────────────────────────────────────
  UGA001: 'matooke steamed green banana',
  UGA002: 'steamed green banana beans pot',
  UGA003: [null, 'Matooke cooked with cow intestines. No generic photo shows this and an offal-and-banana substitute would mislead.'],
  UGA004: 'boiled cassava sweet potato beans',
  UGA005: 'groundnut peanut sauce bowl',
  UGA006: 'food steamed in banana leaf parcel',
  UGA007: 'cooked bamboo shoots',
  UGA008: 'cooked greens peanut sauce',
  UGA009: [null, 'Ghee whipped with rock salt to a pale creamy ceremonial sauce. A photo of any white sauce would misrepresent it, and eshabwe is not in stock libraries.'],
  UGA010: 'mashed beans bowl',
  UGA011: 'ugali white maize meal',
  UGA012: 'amaranth greens sauteed',
  UGA013: 'chapati flatbread',
  UGA014: 'chapati omelette roll wrap',
  UGA015: 'chapati strips with beans',
  UGA016: 'fried pork pieces pan',
  UGA017: 'deep fried pork ribs',
  UGA018: 'beef skewers charcoal grill',
  UGA019: 'roasted plantain charcoal',
  UGA020: 'samosas fried',
  UGA021: 'red amaranth leaves cooked',
  UGA022: 'pumpkin leaves cooked greens',
  UGA023: [null, 'Bitter garden eggs with ground dried silverfish. Two ingredients stock libraries do not carry, in a combination nothing else resembles.'],
  UGA024: 'cassava leaves stew',
  UGA025: 'dried small fish cooked tomato',
  UGA026: 'fish paste jar',
  UGA027: 'fish peanut stew',
  UGA028: 'offal tripe stew',
  UGA029: 'wild mushroom soup',
  UGA030: [null, 'Sweet banana and groundnut steamed in a banana-leaf parcel. The parcel is the dish; an unwrapped substitute shows nothing.'],
  UGA031: 'small banana pancakes fried',
  UGA032: 'mandazi fried dough',
  UGA033: 'fried dough cubes snack',
  UGA034: 'gram flour fritters fried',
  UGA035: 'roasted jackfruit seeds',
  UGA036: 'roasted pumpkin seeds',
  UGA037: 'sesame brittle snaps',
  UGA038: 'roasted sesame seeds',
  UGA039: 'millet porridge bowl',
  UGA040: 'maize porridge bowl',
  UGA041: 'banana porridge bowl',
  UGA042: 'brown beans stew',
  UGA043: 'boiled white sweet potatoes',
  UGA044: 'herbal tea cup leaves',
  UGA045: 'passion fruit juice glass',
  UGA046: 'pineapple juice glass',
  UGA047: 'tamarind drink glass',
  UGA048: 'boiled plantains',
  UGA049: 'bean stew bowl',
  UGA050: 'githeri maize and beans',
  UGA051: [null, 'Fresh shelled beans and pasta with katunkuma bitter berries. The berries are the point and they are not photographed.'],
  UGA052: 'sukuma wiki collard greens',
  UGA053: 'sauteed corn kernels vegetables',
  UGA054: 'fish tomato stew',
  UGA055: [null, 'Street-fried cow lung in instant noodle broth. Nothing in a stock library is this, and a noodle-soup photo would hide the one ingredient that defines it.'],
  UGA056: 'fried potato halves crispy',
  UGA057: 'potato wedges palm oil',
  UGA058: 'potato wrapped egg fried',
  UGA059: 'plantain donuts',
  UGA060: 'banana blossom',
  UGA061: [null, 'Roasted grasshoppers. Stock libraries carry live grasshoppers, not cleaned and roasted nsenene — a live-insect photo would be actively wrong.'],
  UGA062: [null, 'Winged termites, dewinged and roasted or pounded to flour. Same problem as nsenene: the available insect photography is of live insects.'],
  UGA063: [null, 'Roasted crickets. As above — a live cricket is not the dish.'],
  UGA064: 'cooked yam tubers',
  UGA065: 'taro leaves peanut sauce',
  UGA066: 'millet porridge drink',
  UGA067: 'sorghum porridge',
  UGA068: 'mushroom peanut stew banana leaf',
  UGA069: 'cowpea leaves groundnut soup bowl',
  UGA070: [null, 'Sun-dried cowpea leaf ground to a powder. A pantry item, not a plated dish, and not photographed.'],
  UGA071: 'roast goat meat',
  UGA072: [null, 'Small sun-dried Lake Victoria fish in groundnut paste. Nkejje are specific and are not in stock libraries.'],
  UGA073: 'chicken steamed banana leaf',
  UGA074: 'greens sesame peanut sauce',
  UGA075: 'peanut sauce dried fish',
  UGA076: 'green banana vegetable stew',
  UGA077: 'pilau rice',
  UGA078: 'chicken pilau rice',
  UGA079: 'goat pilau rice',
  UGA080: 'peanut sauce with greens',
  UGA081: [null, 'Spider plant and amaranth leaves in groundnut sauce finished with sour milk. Jobyo is not photographed and the sour milk is invisible in any substitute.'],
  UGA082: [null, 'Skinned beans with dried silverfish. A bean-stew photo hides the mukene, which is half the dish.'],
  UGA083: 'plantain sweet potato chips',
  UGA084: [null, 'Ground unroasted sesame, pressed and rolled into balls. The single most distinctive northern Ugandan dish and entirely unphotographed.'],
  UGA085: 'millet drink glass',
  UGA086: [null, 'Millet beer drunk from a shared pot through long straws. The shared pot is the dish; no stock photo has it.'],
  UGA087: [null, 'Lugbara sorghum beer. Not photographed, and a beer glass would misrepresent it entirely.'],
  UGA088: [null, 'Fermented maize beverage. As above.'],
  UGA089: [null, 'Fermented sorghum and honey brew from Kigezi. Not photographed.'],
  UGA090: [null, 'Sorghum drink served in wooden cups. Not photographed.'],
  UGA091: [null, 'Mingled millet and cassava bread — a dark brown mound. Ugali photos are white and would be the wrong colour and the wrong grain.'],
  UGA092: 'cooked pigeon peas bowl',
  UGA093: [null, 'Mashed pigeon peas with shea butter, used to anoint Lango clan leaders. Ceremonial and unphotographed.'],
  UGA094: [null, 'Termites ground to a paste. See the other insect entries.'],
  UGA095: 'mashed sweet potato and beans',
  UGA096: 'sweet potatoes peanut sauce',
  UGA097: [null, 'A brown cooking liquid made from sieved plant ash. Not a plated dish and not photographed.'],
  UGA098: [null, 'Salt made by burning dried salty leaves. Not photographed.'],
  UGA099: [null, 'Pounded wingless termites cooked in leaves. See the other insect entries.'],
  UGA100: [null, 'Juice squeezed from pounded young maize. Not photographed, and a glass of milk would be wrong.'],
  UGA101: [null, 'Ground maize tied in a leaf and boiled into a block. The leaf parcel is the dish.'],
  UGA102: 'dried cassava pieces',
  UGA103: [null, 'Boned fish mashed into groundnut paste. One of very few documented Madi dishes and not photographed.'],
  UGA104: 'mashed skinned beans',
  UGA105: 'mixed roasted nuts and seeds',
  UGA106: 'sweetcorn curry',
  UGA107: 'cassava chips fried',
  UGA108: 'potato bhajia fritters',
  UGA109: 'cow foot trotter soup',
  UGA110: [null, 'Fermented termites rolled into balls and hardened in salted water. See the other insect entries.'],
  UGA111: 'boiled maize and beans pot',
  UGA112: [null, 'Stiff sorghum porridge from Karamoja. Same colour-and-grain problem as karo.'],
  UGA113: 'sweet millet porridge',
  UGA114: 'mango juice glass',
  UGA115: 'lemongrass tea',
  UGA116: 'beans in peanut sauce',
  UGA117: 'boiled maize and beans',
  UGA118: [null, 'Cassava-flour staple, mingled stiff. A white ugali photo is the wrong grain.'],
  UGA119: 'cowpea leaves sesame sauce',
  UGA120: 'sesame and peanut paste bowl',
  // ─── GHANA ──────────────────────────────────────────────────
  // Written against each dish's own entry, so the query describes what
  // is actually on the plate rather than repeating a name Pexels has
  // never seen. Where several dishes genuinely look alike — six
  // groundnut soups, three jollofs — the queries differ a little and
  // the fetcher's dedupe guard hands each one a different photograph.

  GHA001: 'fufu dough ball with soup',
  GHA002: 'white dough ball soup bowl',
  GHA003: 'rice balls in soup bowl',
  GHA004: 'white rice balls plate',
  GHA005: 'rice balls groundnut soup',
  GHA006: 'boiled yam and plantain plate',
  GHA007: 'mashed plantain with boiled egg',
  GHA008: 'mashed yam palm oil egg',
  GHA009: 'spiced mashed yam bowl',
  GHA010: 'thick corn porridge palm oil stew',
  GHA011: 'goat meat broth tomato soup',
  GHA012: 'chicken light broth tomato soup',
  GHA013: 'peanut soup with chicken bowl',
  GHA014: 'groundnut soup chilli bowl',
  GHA015: 'peanut soup okra eggplant',
  GHA016: 'west african peanut stew',
  GHA017: 'creamy peanut soup bowl',
  GHA018: 'groundnut soup with meat',
  GHA019: 'palm nut soup red broth',
  GHA020: 'palm oil soup with fish',
  GHA021: 'red palm soup bowl',
  GHA022: 'dark green leaf soup bowl',
  GHA023: 'spinach stew with boiled plantain',
  GHA024: 'spinach stew melon seed',
  GHA025: 'egg and tomato stew pan',
  GHA026: 'african eggplant stew',
  GHA027: 'eggplant stew dried shrimp',
  GHA028: 'pepper and onion relish bowl',
  GHA029: 'mashed eggplant relish bowl',
  GHA030: 'fish stew red palm oil',
  GHA031: 'blended tomato pepper sauce',
  GHA032: 'roasted red pepper tomato sauce',
  GHA033: 'peanut sauce in bowl',
  GHA034: 'orange root vegetable porridge',
  GHA035: 'cassava grains couscous bowl',
  GHA036: 'yam porridge smoked fish',
  GHA037: 'corn dough wrapped in husk',
  GHA038: 'fermented corn dough balls',
  GHA039: 'white corn dough ball plate',
  GHA040: 'blended corn milk drink glass',
  GHA041: 'banku corn dough ball',
  GHA042: 'smooth white dough ball soup',
  GHA043: 'cassava dough ball',
  GHA044: 'millet dough ball with soup',
  GHA045: 'rice porridge with milk bowl',
  GHA046: 'corn dough with beans plate',
  GHA047: 'tomato gravy sauce pan',
  GHA048: 'fried plantain fritter balls',
  GHA049: 'fried spiced plantain cubes',
  GHA050: 'kelewele fried plantain cubes',
  GHA051: 'black chilli pepper sauce jar',
  GHA052: 'dark chilli oil sauce bowl',
  GHA053: 'green chilli sauce bowl',
  GHA054: 'plantain pancake fried',
  GHA055: 'cassava granules egg tomato',
  GHA056: 'gari with egg and tomato plate',
  GHA057: 'fried corn dough balls',
  GHA058: 'rice and beans waakye plate',
  GHA059: 'brown rice and beans plate',
  GHA060: 'lamb stew tomato bowl',
  GHA061: 'spiced beef kebab skewers grilled',
  GHA062: 'suya beef skewers spice',
  GHA063: 'goat meat skewers grilled',
  GHA064: 'ground peanut spice powder bowl',
  GHA065: [null, 'Singed and boiled cow skin. Stock libraries have nothing for it, and any other cut of meat would misrepresent what is on the plate.'],
  GHA066: [null, 'Fermented salted fish used as a seasoning paste. Not photographed, and a photo of fresh fish would be a different ingredient.'],
  GHA067: 'fresh pepper sauce mortar',
  GHA068: 'cassava flour biscuits cookies',
  GHA069: 'bean stew with fried plantain',
  GHA070: 'black eyed bean stew fish',
  GHA071: 'red bean stew palm oil',
  GHA072: 'fried peanut snack sticks',
  GHA073: 'millet swallow with green soup',
  GHA074: 'jute leaf green soup bowl',
  GHA075: 'green leaf soup bowl broth',
  GHA076: 'spiced millet porridge bowl',
  GHA077: 'fried bean fritter balls',
  GHA078: [null, 'Fermented locust beans pressed into cakes. A generic spice or bean photo would show a different thing entirely.'],
  GHA079: 'millet drink in glass',
  GHA080: 'steamed bean pudding slice',
  GHA081: 'sesame seed soup bowl',
  GHA082: 'grilled guinea fowl',
  GHA083: 'bambara beans stew bowl',
  GHA084: 'fried white cheese cubes',
  GHA085: 'millet beer in calabash',
  GHA086: 'local beer gourd calabash',
  GHA087: 'jute mallow soup bowl',
  GHA088: 'okra soup bowl green',
  GHA089: 'okra stew bowl',
  GHA090: 'fried cassava dough balls',
  GHA091: 'steamed cassava couscous',
  GHA092: 'peanut balls snack plate',
  GHA093: 'corn flour palm stew bowl',
  GHA094: 'grilled tilapia fish plate',
  GHA095: 'whole grilled fish charcoal',
  GHA096: 'grilled prawns skewer',
  GHA097: 'jollof rice with chicken',
  GHA098: 'jollof rice in pot',
  GHA099: 'one pot jollof rice',
  GHA100: 'red tomato sauce in pan',
  GHA101: 'ground spice mix in bowl',
  GHA102: 'crispy fried chicken strips',
  GHA103: 'fonio grain cooked bowl',
  GHA104: 'grilled sardines tomato sauce',
  GHA105: 'spinach melon seed curry',
  GHA106: 'beef skewers grilled peanut',
  GHA107: 'coconut rice bowl',
  GHA108: 'coated spiced peanuts snack',
  GHA109: 'hibiscus drink glass ice',
  GHA110: 'hibiscus iced tea pitcher',
  GHA111: 'white milk pudding glass dessert',
  GHA112: 'twisted fried dough snack',
  GHA113: 'coconut milk and fresh coconut',
  GHA114: 'african fried dough balls',
  GHA115: 'fried dough balls sugar',
  GHA116: 'peanut brittle slab',
  GHA117: 'peanut caramel candy pieces',
  GHA118: 'soft sweet bread loaf',
  GHA119: 'baked meat pie pastry',
  GHA120: 'grilled plantain with peanuts',

  // ─── NIGERIA ────────────────────────────────────────────────

  NGA001: 'dark brown yam flour swallow',
  NGA002: 'jute leaf green soup',
  NGA003: 'green soup melon seed',
  NGA004: 'bean soup smooth yellow',
  NGA005: 'bean soup assorted beef',
  NGA006: 'three soups on one plate',
  NGA007: 'pounded yam white swallow',
  NGA008: 'spinach stew red palm oil',
  NGA009: 'leafy green stew bowl',
  NGA010: 'seafood spinach stew',
  NGA011: 'melon seed soup lumps',
  NGA012: 'melon seed soup fried',
  NGA013: 'spinach melon seed stew',
  NGA014: 'lumpy egusi soup bowl',
  NGA015: 'okra soup draw bowl',
  NGA016: 'green pepper stew boiled egg',
  NGA017: 'ofada stew brown rice',
  NGA018: 'pepper stew with boiled eggs',
  NGA019: 'red pepper stew base',
  NGA020: 'yam pottage porridge',
  NGA021: 'water yam pottage lumps',
  NGA022: 'steamed bean pudding slices',
  NGA023: 'steamed bean pudding cups',
  NGA024: 'bean pudding steamed in leaves',
  NGA025: 'plain steamed bean pudding',
  NGA026: 'fried pepper sauce bowl',
  NGA027: 'roasted pepper relish bowl',
  NGA028: 'fried bean cakes akara',
  NGA029: 'fried bean fritters street',
  NGA030: 'mashed beans pepper sauce',
  NGA031: 'dark fried pepper onion sauce',
  NGA032: 'brown beans pepper sauce',
  NGA033: 'mashed beans chilli oil',
  NGA034: 'peppered goat meat chunks',
  NGA035: 'corn pudding wrapped leaf',
  NGA036: 'soft white bread loaf sliced',
  NGA037: 'pepper soup goat meat',
  NGA038: 'palm fruit broth soup',
  NGA039: 'melon seed soup bowl thick',
  NGA040: 'palm oil pepper soup fish',
  NGA041: 'ogbono draw soup bowl',
  NGA042: 'cassava starch swallow',
  NGA043: 'palm fruit cream pot',
  NGA044: 'palm fruit soup fish',
  NGA045: 'palm nut soup delta style',
  NGA046: 'palm fruit broth seafood',
  NGA047: 'pepper soup with yam',
  NGA048: 'white pepper soup catfish',
  NGA049: 'white soup bitter leaf',
  NGA050: 'green leaf soup thick',
  NGA051: 'bitter leaf soup bowl',
  NGA052: 'thick vegetable soup bowl',
  NGA053: 'palm fruit stew rice',
  NGA054: [null, 'Potash and palm oil emulsion used to dress abacha. A photo of oil in a bowl would not show the dish.'],
  NGA055: 'shredded cassava salad',
  NGA056: 'cassava salad garden eggs',
  NGA057: [null, 'Fermented oil bean slices. Not in stock libraries, and a photo of fresh beans would be a different ingredient.'],
  NGA058: 'peppered cow foot bowl',
  NGA059: 'spiced cow leg platter',
  NGA060: 'spiced goat head platter',
  NGA061: 'african breadfruit porridge',
  NGA062: 'steamed bambara bean pudding',
  NGA063: 'vegetable soup leafy thick',
  NGA064: 'pumpkin leaf soup bowl',
  NGA065: 'shredded leaf soup bowl',
  NGA066: 'palm fruit leaf soup',
  NGA067: 'clear white fish soup',
  NGA068: 'dark green leaf soup',
  NGA069: 'palm oil rice dish',
  NGA070: 'okra and fish soup',
  NGA071: 'cocoyam parcels in leaves',
  NGA072: 'water yam parcels soup',
  NGA073: 'okra soup with fish',
  NGA074: 'mixed seafood pepper soup',
  NGA075: 'plantain pottage fish',
  NGA076: 'mashed yam and plantain balls',
  NGA077: 'catfish pepper soup bowl',
  NGA078: 'pepper soup broth bowl',
  NGA079: 'suya spice powder bowl',
  NGA080: 'ground spice blend plate',
  NGA081: 'dark spice powder mortar',
  NGA082: 'suya skewers grilled beef',
  NGA083: 'dried spiced meat sheets',
  NGA084: 'dried beef jerky strips',
  NGA085: 'maize flour swallow white',
  NGA086: 'pounded rice swallow ball',
  NGA087: 'baobab leaf soup dark',
  NGA088: 'pumpkin soup peanut',
  NGA089: 'blended pumpkin soup bowl',
  NGA090: 'moringa leaf soup bowl',
  NGA091: 'shredded dried beef floss',
  NGA092: 'shredded spiced mutton',
  NGA093: 'peanut snack sticks fried',
  NGA094: 'bean flour dumplings',
  NGA095: 'rice cakes fried round',
  NGA096: 'small round rice pancakes',
  NGA097: 'tiger nut peanut sweet bar',
  NGA098: 'peanut millet drink glass',
  NGA099: 'fermented milk glass',
  NGA100: 'millet dough balls',
  NGA101: 'millet balls in sour milk',
  NGA102: 'tiger nut milk drink glass',
  NGA103: 'catfish stew tomato bowl',
  NGA104: 'cocoyam porridge bowl',
  NGA105: [null, 'Soup drawn from okoho stalk, a wild climbing plant. The stalk is not photographed and no other soup looks like it.'],
  NGA106: [null, 'Okoho soup with bushmeat. Same stalk problem, and bushmeat is not something to illustrate with stock photography.'],
  NGA107: 'fonio acha grain cooked',
  NGA108: 'small grain porridge bowl',
  NGA109: 'party jollof rice smoky',
  NGA110: 'jollof rice and chicken plate',
  NGA111: 'jollof rice tomato stew',
  NGA112: 'puff puff fried dough balls',
  NGA113: 'hibiscus zobo drink glass',
  NGA114: 'red cocktail drink tall glass',
  NGA115: 'fried coconut rice plate',
  NGA116: 'chicken in red hibiscus sauce',
  NGA117: 'roasted corn on cob street',
  NGA118: 'jute leaf soup smooth green',
  NGA119: 'yellow bean soup bowl',
  NGA120: [null, 'Potash, a mineral salt sold in lumps. A photo of salt or stone would misrepresent what it is and this entry carries a safety warning that matters more than a picture.'],

  // ─── ETHIOPIA ───────────────────────────────────────────────
  ETH001: 'injera flatbread platter',
  ETH002: 'teff injera spongy bread',
  ETH004: 'round spiced bread loaf',
  ETH006: 'decorated sweet round bread',
  ETH007: 'thin sourdough flatbread rolled',
  ETH009: 'thick wheat porridge bowl',
  ETH010: 'torn flatbread pieces spiced sauce',
  ETH011: 'cooked cracked wheat bowl',
  ETH013: 'plain steamed white rice',
  ETH014: 'thin barley gruel mug',
  ETH015: [null, 'Roasted barley powder is a pale loose flour, and any photo of it would be indistinguishable from any other milled grain.'],
  ETH016: 'boiled barley grains bowl',
  ETH017: 'boiled wheat berries bowl',
  ETH020: 'millet porridge clay bowl',
  ETH021: 'red berbere beef stew',
  ETH023: 'sizzling beef tibs clay pot',
  ETH024: 'crispy dry fried beef cubes',
  ETH025: 'lamb tibs skillet onions',
  ETH027: 'mild turmeric yellow beef stew',
  ETH035: 'clear lamb broth soup bowl',
  ETH038: 'beef stew with carrots potatoes',
  ETH039: 'lamb curry with injera',
  ETH040: 'beef curry with injera',
  ETH041: 'dark red lamb stew berbere',
  ETH042: 'pale yellow lamb stew',
  ETH045: 'beef tendon stew bowl',
  ETH046: 'tripe stew red sauce',
  ETH047: 'beef liver onion stew',
  ETH048: 'dried beef strips drying',
  ETH049: 'shredded flatbread dried beef',
  ETH050: 'lamb shoulder chunks pan fried',
  ETH051: 'fiery red beef stew injera',
  ETH052: 'beef tibs chilli paste sauce',
  ETH053: 'warmed kitfo minced beef',
  ETH054: 'beef stew cinnamon spices bowl',
  ETH057: 'beef and lentil stew pot',
  ETH058: 'spiced beef chunks butter sauce',
  ETH059: 'roasted leg of lamb',
  ETH061: 'doro wot chicken stew',
  ETH062: 'mild yellow chicken stew',
  ETH063: 'chicken tibs sauteed peppers',
  ETH064: 'whole roasted spiced chicken',
  ETH065: 'chicken drumstick stew bowl',
  ETH066: 'berbere chicken thighs',
  ETH068: 'chicken broth soup bowl',
  ETH069: 'torn injera chicken sauce',
  ETH070: 'chicken lentil stew plate',
  ETH071: 'doro wot boiled eggs injera',
  ETH073: 'chicken stew clay bowl injera',
  ETH074: 'chicken pieces spiced butter sauce',
  ETH075: 'chicken stew tomato onion spices',
  ETH078: 'cubed chicken chilli butter',
  ETH079: 'chicken stew with hard boiled eggs',
  ETH081: 'red fish stew berbere',
  ETH083: 'fried fish cubes onion pan',
  ETH084: 'fish curry injera plate',
  ETH085: 'grilled whole fish spice rub',
  ETH086: 'tilapia stew tomato sauce',
  ETH087: 'fried lake tilapia fillets',
  ETH088: 'fish fillet red chilli sauce',
  ETH090: 'fish soup clear broth bowl',
  ETH092: [null, 'Spiced clarified butter is just golden fat in a jar, so a photo would show nothing that distinguishes it from ordinary ghee.'],
  ETH095: 'golden honey wine flask',
  ETH096: 'crumbly fresh white cheese',
  ETH098: 'smoked fish fillets',
  ETH099: 'tomato onion green chilli salad',
  ETH101: 'red lentil stew injera',
  ETH108: 'cooked mustard greens bowl',
  ETH109: 'green beans carrot turmeric stew',
  ETH110: 'yellow split pea stew',
  ETH111: 'brown lentil curry bowl',
  ETH113: 'black eyed pea stew',
  ETH114: 'stewed spinach garlic bowl',
  ETH115: 'cabbage potato carrot turmeric stew',
  ETH119: 'chopped tomato jalapeno salad',
  ETH120: 'lettuce tomato cucumber salad',
  ETH121: 'vegan injera platter stews',
  ETH123: 'shiro chickpea paste torn injera',
  ETH124: 'lentils and spinach stew',
  ETH125: 'eggplant tomato stew bowl',
  ETH127: 'pumpkin chunks spiced stew',
  ETH129: 'fenugreek leaf stew bowl',
  ETH132: 'red lentil stew boiled egg',
  ETH133: 'thin lentil soup bowl',
  ETH134: 'mixed vegetables berbere sauce',
  ETH135: 'lentil vegetable stew pot',
  ETH137: 'ful medames fava beans bowl',
  ETH140: 'large vegan injera feast platter',
  ETH142: 'bright red chilli powder bowl',
  ETH143: [null, 'An extended-spice clarified butter looks like plain melted fat, so no photo could honestly show what the long spice infusion produced.'],
  ETH144: 'dark red chilli paste bowl',
  ETH145: 'fresh cheese with chopped herbs',
  ETH147: 'diced tomato salad bowl',
  ETH149: 'green chilli paste bowl',
  ETH151: 'collard greens sauce bowl',
  ETH154: 'lemon wedges chilli spice',
  ETH155: 'red chilli infused oil jar',
  ETH156: [null, 'Shiro powder is a beige milled flour that no photograph could tell apart from any other ground pulse.'],
  ETH168: 'fried meat samosa triangles',
  ETH170: 'honey glazed sweet bread loaf',
  ETH171: 'shredded flatbread butter berbere',
  ETH172: 'injera drizzled with honey',
  ETH178: 'sweet potato fries plate',
  ETH181: 'small thick pancakes stack',
  ETH185: 'stuffed boiled eggs halves',
  ETH187: 'fried samosa chickpea filling',
  ETH188: 'peanut brittle squares',
  ETH190: 'street snack platter samosas skewers',
  ETH193: 'sweet patterned round bread slices',
  ETH198: 'sesame honey candy bars',
  ETH200: 'sliced papaya mango banana platter',
  ETH201: 'dark teff porridge honey',
  ETH204: 'small crunchy dough nuggets',
  ETH205: [null, 'This sweet is defined by the New Year occasion rather than by a fixed appearance, so any photo would be a stand-in for something else.'],
  ETH206: [null, 'The dish is identified by its Christmas setting rather than a recognisable plated form, so no photo could honestly represent it.'],
  ETH208: 'tamarind candy pieces',
  ETH210: 'assorted sweets fruit dessert platter',
  ETH211: [null, 'The coffee ceremony is a sequence of roasting, brewing and serving rituals that no single still photo can honestly depict.'],
  ETH212: 'black coffee small cups',
  ETH213: 'spiced tea glass cinnamon',
  ETH214: 'warm barley drink mug',
  ETH215: 'honey mead glass flask',
  ETH216: 'cloudy homebrew beer gourd',
  ETH217: 'thick fermented grain drink glass',
  ETH218: 'cloudy fermented barley drink jug',
  ETH219: 'thick mango juice glass',
  ETH220: 'tamarind juice glass',
  ETH221: 'layered avocado juice glass',
  ETH225: 'passion fruit juice pitcher',
  ETH227: 'red hibiscus tea glass',
  ETH228: 'warm cinnamon milk cup',
  ETH229: 'black coffee with butter cup',
  ETH230: [null, 'This is a guide covering many different drinks rather than one served item, so a single photo would misrepresent it.'],
  ETH231: 'lamb stew berbere clay pot',
  ETH232: 'kitfo raw minced beef plate',
  ETH233: 'buttery grain porridge bowl',
  ETH234: 'dried meat cubes jar',
  ETH235: 'red lentil stew clay dish',
  ETH236: 'spicy beef stew injera platter',
  ETH237: 'kitfo with cheese and greens',
  ETH239: [null, 'Chuko is barley flour kneaded with spiced butter into a plain beige mound, which no photo could identify as this dish.'],
  ETH240: 'grilled camel meat chunks',
  ETH241: 'diced beef suqaar skillet',
  ETH242: 'spiced meat broth soup bowl',
  ETH243: 'thick enset bread slices',
  ETH244: [null, 'Mich is defined by its enset fermentation process and looks like an undifferentiated pale dough in any photograph.'],
  ETH246: 'thick enset flatbread griddle',
  ETH247: [null, 'This covers forest harvesting and roasting practices rather than a plated item a photograph could show.'],
  ETH248: 'boiled enset root pieces',
  ETH249: 'grilled fish with sorghum porridge',
  ETH253: 'torn bread soaked spicy sauce',
  ETH255: 'azuki beans rice butter bowl',
  ETH257: 'enset bread lamb stew',
  ETH258: 'fava bean stew with flatbread',
  ETH259: 'patterned round celebration bread',
  ETH260: [null, 'A sampler assembled to represent many regions at once has no single honest appearance for a photo to match.'],
  ETH261: [null, 'A ceremonial Meskel festival feast rather than one specific dish with a fixed look.'],
  ETH263: 'honey glazed herb stew bowl',
  ETH265: [null, 'A composed royal banquet of many dishes, so any one photo would falsely stand in for the whole feast.'],
  ETH266: [null, 'Pilgrimage fare defined by its occasion and setting rather than by an appearance a photo could capture.'],
  ETH267: 'fried fish platter lemon',
  ETH269: [null, 'A reconstructed historical feast with no agreed plated form that a photograph could honestly show.'],
  ETH270: [null, 'A tour across many vendors and stalls rather than one dish on a plate.'],
  ETH271: [null, 'A cultural feast built around enset processing rather than a single dish with a recognisable look.'],
  ETH272: [null, 'A full holiday menu of many courses, so no one photo could honestly represent it.'],
  ETH273: [null, 'A guide to coffee customs rather than a drink that can be plated and photographed.'],
  ETH274: [null, 'A guide to beekeeping and honey traditions rather than a prepared dish.'],
  ETH275: [null, 'A guide to the spice blend history, which a bowl of chilli powder would not honestly convey.'],
  ETH276: [null, 'A guide to injera fermentation and its social role, which no single plate photo can stand for.'],
  ETH277: [null, 'This covers a whole city food scene rather than one dish, so any photo would be arbitrary.'],
  ETH278: [null, 'Defined by the fasting calendar rather than by any one dish with a specific appearance.'],
  ETH280: [null, 'An assembled diversity sampler with no established appearance a stock photo could match.'],
  ETH282: 'berbere grilled chicken skewers',
  ETH283: 'beef tibs grain bowl',
  ETH285: 'spiced red seasoned fries',
  ETH288: 'dark teff pancakes stack berries',
  ETH289: 'green avocado smoothie glass',
  ETH292: 'colorful vegetable bowls platter',
  ETH293: 'spiced rice bowl vegetables',
  ETH295: 'iced coffee milkshake glass',
  ETH297: 'injera wrap rolled filling',
  ETH298: 'plated modern dessert selection',
  ETH299: [null, 'A house signature combination invented for the brand, so no existing stock photo shows this meal.'],
  ETH300: [null, 'A branded composite heritage platter with no established appearance for a photo to match.'],

  // ─── ITALY ──────────────────────────────────────────────────
  ITA004: 'pane pugliese rustic loaf',
  ITA010: 'schiacciata flatbread olive oil',
  ITA011: 'polenta cornmeal wooden board',
  ITA012: 'creamy soft polenta bowl',
  ITA013: 'fried polenta squares crisp',
  ITA014: 'potato gnocchi raw semolina board',
  ITA018: 'plain white risotto plate',
  ITA019: 'arancini rice balls fried',
  ITA021: 'spaghetti carbonara guanciale egg',
  ITA023: 'cacio e pepe pasta bowl',
  ITA024: 'rigatoni amatriciana tomato guanciale',
  ITA025: 'pasta alla norma eggplant ricotta',
  ITA032: 'baked manicotti ricotta tubes',
  ITA034: 'tortellini in brodo broth bowl',
  ITA037: 'linguine vongole clams shells',
  ITA039: 'bucatini amatriciana bowl pecorino',
  ITA043: 'pasta e ceci chickpea soup',
  ITA045: 'lemon cream pasta zest',
  ITA046: 'spaghetti with meatballs plate',
  ITA048: 'tortellini creamy alfredo sauce',
  ITA052: 'agnolotti del plin butter sage',
  ITA053: 'culurgiones sardinian stuffed dumplings',
  ITA054: 'malloreddus sausage saffron sauce',
  ITA055: 'strozzapreti meat ragu twisted pasta',
  ITA056: 'pici aglione thick hand rolled',
  ITA057: 'casoncelli filled pasta butter bacon',
  ITA059: 'garganelli prosciutto cream peas',
  ITA060: 'scialatielli seafood pasta mussels',
  ITA061: 'spaghetti puttanesca olives capers',
  ITA063: 'corzetti pasta discs walnut sauce',
  ITA064: 'anolini small pasta in broth',
  ITA065: 'passatelli breadcrumb pasta broth',
  ITA066: 'tajarin egg noodles shaved truffle',
  ITA067: 'spaghetti nerano fried zucchini',
  ITA068: 'cavatelli broccoli rabe greens',
  ITA069: 'sagne pasta with beans rustic',
  ITA070: 'strangozzi black truffle umbria',
  ITA071: 'spaghetti alla chitarra lamb ragu',
  ITA073: 'bigoli pasta onion anchovy sauce',
  ITA075: 'spaghetti with mussels shells',
  ITA076: 'troccoli pasta fish ragu',
  ITA077: 'umbricelli sausage cream truffle',
  ITA079: 'maltagliati borlotti bean soup',
  ITA084: 'zabaglione marsala custard glass',
  ITA087: 'saffron risotto milanese yellow',
  ITA089: 'seafood risotto prawns mussels',
  ITA093: 'pollo alla cacciatora braised chicken',
  ITA095: 'baccala vicentina salt cod polenta',
  ITA098: 'eggplant involtini rolls ricotta',
  ITA105: 'cantucci almond biscotti vin santo',
  ITA106: 'struffoli honey dough balls',
  ITA108: 'minestrone genovese pesto vegetable soup',
  ITA112: 'arancini cut open meat ragu',
  ITA114: 'frico cheese potato crisp',
  ITA115: 'polenta taragna buckwheat cheese',
  ITA116: 'fontina cheese fondue bread',
  ITA121: 'pasta con le sarde sardines fennel',
  ITA122: 'panelle chickpea fritters sicilian',
  ITA123: 'sarde beccafico stuffed sardines',
  ITA124: 'swordfish rolls breadcrumb filling',
  ITA128: 'focaccia barese tomato olives',
  ITA129: 'offal stew on pitta bread',
  ITA131: 'cacciucco tuscan seafood stew',
  ITA132: 'pasta frittata wedge sliced',
  ITA136: 'cotoletta milanese breaded veal',
  ITA140: 'seadas fried cheese pastry honey',
  ITA143: 'chickpea chestnut soup bowl',
  ITA144: 'ventricina spicy salami slices',
  ITA146: 'cheese egg balls tomato sauce',
  ITA147: 'aged pecorino wedge with honey',
  ITA148: 'crescia flatbread layered griddle',
  ITA149: 'lagane pasta ribbons chickpeas',
  ITA150: 'cialledda bread tomato onion salad',
  ITA155: 'vincisgrassi baked lasagna marche',
  ITA156: 'braised rabbit olives pine nuts',
  ITA159: 'risi e bisi rice peas',
  ITA160: 'baccala mantecato whipped cod crostini',
  ITA162: 'oxtail stew celery tomato roman',
  ITA163: 'trippa alla romana tripe tomato',
  ITA166: 'puntarelle salad anchovy dressing',
  ITA167: 'pasta zozzona sausage egg tomato',
  ITA168: 'stuffed zucchini flowers fried',
  ITA170: 'acquacotta bread soup poached egg',
  ITA172: 'torta pasqualina chard egg pie',
  ITA177: 'erbazzone spinach savory tart',
  ITA179: 'tortelli erbette chard filled pasta',
  ITA183: 'jota soup sauerkraut beans pork',
  ITA185: 'cabbage bread fontina baked soup',
  ITA186: 'beef wine stew with polenta',
  ITA187: 'cavatelli sausage tomato sauce',
  ITA188: 'roast pork paprika chilli molise',
  ITA189: 'arrosticini lamb skewers grill',
  ITA191: 'torta al testo umbrian flatbread',
  ITA193: 'sardinian suckling pig roast',
  ITA195: 'stewed peppers potatoes eggplant pan',
  ITA198: 'sardella calabrese spicy fish spread',
  ITA199: 'fileja pasta goat ragu',
  ITA206: 'radicchio risotto purple treviso',
  ITA207: 'pumpkin risotto orange creamy',
  ITA208: 'spaghetti seafood baked parchment parcel',
  ITA209: 'mussel soup tomato broth bowl',
  ITA212: 'breaded chicken breast cutlet lemon',
  ITA213: 'cannellini beans sage tomato pan',
  ITA214: 'sauteed neapolitan broccoli greens garlic',
  ITA215: 'carciofi alla romana braised artichokes',
  ITA216: 'sauteed chicory garlic chilli',
  ITA217: 'salt cod fritters golden plate',
  ITA219: 'pork cabbage stew lombard',
  ITA220: 'diced eggplant tomato basil pan',
  ITA222: 'zeppole fried dough rings sugar',
  ITA226: 'pasta and potato soupy neapolitan',
  ITA227: 'casatiello neapolitan savory bread ring',
  ITA229: 'braised castelluccio lentils bowl',
  ITA232: 'strangolapreti bread spinach dumplings',
  ITA234: 'musetto sausage with brovada turnips',
  ITA235: 'horseradish potato baked omelette',
  ITA237: 'salt cod tomato olives stew',
  ITA240: 'easter bread ring whole eggs',
  ITA244: 'swordfish steak capers olives sauce',
  ITA246: 'milanese fried meatballs patties',
  ITA247: 'venetian calf liver onions',
  ITA248: 'grape focaccia sweet bread wine grapes',
  ITA249: 'pansotti walnut sauce ligurian',
  ITA250: 'gramigna pasta sausage cream',
  ITA251: 'baked rice potato mussel casserole',
  ITA252: 'adriatic fish stew tomato bowl',
  ITA253: 'crepe strips in chicken broth',
  ITA254: [null, 'No stock library reliably shows Bergamo\'s sweet marzipan dome studded with tiny chocolate birds, and the name itself returns the unrelated savoury polenta-and-game dish.'],
  ITA255: 'spaghetti bottarga grated mullet roe',
  ITA257: 'stockfish potato pepper stew',
  ITA258: 'small cheeses chilli oil marinade',
  ITA259: 'short pasta ribbons bean stew',
  ITA260: 'dark chocolate almond flourless cake',
  ITA262: 'sarde in saor onions raisins',
  ITA267: 'stuffed veal breast sliced cold',
  ITA268: 'busiate trapanese almond tomato pesto',
  ITA269: 'tripe bean soup milanese bowl',
  ITA270: 'dark soft sausage with mashed potato',
  ITA271: 'spreadable salami on bread slices',
  ITA272: 'rustic pork rib stew tomato',
  ITA274: 'herb frittata wedges green',
  ITA275: 'thinly sliced cured mountain meat',
  ITA276: 'baked bread cheese broth casserole',
  ITA277: [null, 'Nothing in the stock libraries shows Abruzzo\'s lamb-offal bundles tied up inside chard leaves, and any lamb-stew photo would misrepresent the dish entirely.'],
  ITA278: 'chestnut velvet soup cream swirl',
  ITA279: 'braided sweet easter bread glaze',
  ITA284: 'pasta ncasciata baked eggplant sicilian',
  ITA286: 'fried soft shell crabs plate',
  ITA287: 'sausages with cannellini beans tomato',
  ITA288: 'ligurian green vegetable savory tart',
  ITA289: 'cappelletti in clear broth bowl',
  ITA293: 'hand pulled long pasta tomato sauce',
  ITA294: 'spiked espresso layered glass',
  ITA298: 'polenta with melted fontina cheese',
  ITA300: 'fish acqua pazza cherry tomatoes',
  ITA304: 'sicilian fish soup saffron broth',

  // ─── KENYA ──────────────────────────────────────────────────
  KEN001: 'white ugali maize meal',
  KEN002: 'sauteed collard greens onions',
  KEN003: 'beef stew tomato gravy',
  KEN004: 'layered chapati flatbread stack',
  KEN005: 'githeri maize beans bowl',
  KEN006: 'nyama choma grilled goat',
  KEN007: 'tomato onion coriander salad',
  KEN009: 'spiced pilau rice chicken',
  KEN010: 'mashed potatoes with greens',
  KEN011: 'mashed peas potato maize',
  KEN012: 'grilled fish coconut sauce',
  KEN013: 'small dried fish stew',
  KEN014: 'red beans coconut sauce',
  KEN015: 'mandazi fried dough triangles',
  KEN016: 'mahamri swahili fried bread',
  KEN017: 'battered fried potato chunks',
  KEN018: 'bhajia fried potato slices',
  KEN022: 'chicken in coconut curry',
  KEN023: 'dehulled maize bean stew',
  KEN024: 'free range chicken stew',
  KEN025: 'green banana stew pot',
  KEN026: 'boiled maize cowpeas mix',
  KEN027: [null, 'Fermented milk cured in a soot-lined gourd looks like plain milk in any photo, so no stock image can show what makes it mursik.'],
  KEN028: 'cooked amaranth greens bowl',
  KEN029: 'finger millet porridge cup',
  KEN030: 'green gram stew bowl',
  KEN031: 'sauteed diced beef cubes',
  KEN033: 'boiled sweet potato pieces',
  KEN034: 'boiled taro root slices',
  KEN035: 'boiled cassava chunks plate',
  KEN036: 'cassava in creamy coconut',
  KEN037: 'mashed sweet potato bowl',
  KEN038: 'mashed taro paste bowl',
  KEN039: 'white coconut rice bowl',
  KEN041: 'braised beef stew potatoes',
  KEN042: 'pan fried beef tomatoes',
  KEN043: 'beef pilau rice spices',
  KEN044: 'beef curry thick sauce',
  KEN048: 'tripe stew honeycomb pieces',
  KEN049: 'fried tripe pieces plate',
  KEN050: 'beef bone broth soup',
  KEN051: 'goat meat stew bowl',
  KEN052: 'fried goat meat pieces',
  KEN053: 'goat pilau spiced rice',
  KEN054: 'goat curry bone in',
  KEN055: 'roasted goat ribs rack',
  KEN056: 'goat bone soup broth',
  KEN058: 'lamb stew vegetables pot',
  KEN059: 'grilled lamb chops plate',
  KEN060: 'lamb curry sauce bowl',
  KEN062: 'pilau rice chicken drumstick',
  KEN063: 'chicken curry tomato gravy',
  KEN066: 'grilled chicken quarters charcoal',
  KEN070: 'clear chicken soup bowl',
  KEN072: 'tilapia simmered tomato onion',
  KEN073: 'tilapia fillet curry bowl',
  KEN074: 'whole grilled tilapia fish',
  KEN075: 'silver sardines fried onions',
  KEN076: 'fish curry coconut milk',
  KEN077: 'breaded fish fingers fried',
  KEN079: 'prawn curry red sauce',
  KEN081: 'cooked nightshade leafy greens',
  KEN082: 'cooked pumpkin leaves greens',
  KEN085: 'mixed cooked leafy vegetables',
  KEN088: 'okra stew sliced pods',
  KEN089: 'eggplant stew tomato pot',
  KEN090: 'mixed vegetable medley sauteed',
  KEN092: 'egg curry in sauce',
  KEN095: 'halved boiled eggs curry',
  KEN097: 'biryani rice fried onions',
  KEN098: 'vegetable pilau rice peas',
  KEN101: 'fried cardamom coconut buns',
  KEN102: 'coconut mandazi fried dough',
  KEN103: 'triangular flatbread pieces plate',
  KEN105: 'sugared fried dough puffs',
  KEN106: 'dark millet ugali block',
  KEN107: 'brown sorghum stiff porridge',
  KEN108: 'cassava flour stiff porridge',
  KEN109: 'millet porridge bowl spoon',
  KEN110: 'sorghum porridge thick bowl',
  KEN111: [null, 'A sausage stuffed with blood and offal has no honest stock equivalent; any grilled-sausage photo would misrepresent it.'],
  KEN113: 'french fries masala sauce',
  KEN114: 'french fries omelette wedge',
  KEN116: 'turmeric battered potato bites',
  KEN117: 'samosa triangles fried snack',
  KEN119: 'cassava fries golden sticks',
  KEN120: 'roasted peanuts in shells',
  KEN121: 'kidney beans coconut stew',
  KEN123: 'fish chunks tomato stew',
  KEN124: 'beef coconut curry bowl',
  KEN126: 'steamed rice flour cake',
  KEN127: 'fried potato fritters coconut',
  KEN128: 'fish in tamarind sauce',
  KEN129: 'cassava cubes coconut milk',
  KEN130: 'lentils cooked coconut milk',
  KEN132: 'honey lime cocktail glass',
  KEN133: 'tamarind juice glass ice',
  KEN134: 'passion fruit juice tall glass',
  KEN136: 'sugarcane juice glass straw',
  KEN137: 'hibiscus iced drink glass',
  KEN138: 'avocado shake tall glass',
  KEN139: 'fresh coconut water straw',
  KEN141: 'coconut peanut candy squares',
  KEN142: 'sweet potato pudding dish',
  KEN143: 'coconut rice pudding bowl',
  KEN145: 'peanut brittle broken pieces',
  KEN149: 'banana fritters fried golden',
  KEN150: 'coconut cake slice shredded',
  KEN152: 'boiled peanuts in shell',
  KEN154: 'crispy cassava chips bowl',
  KEN157: 'tamarind candy balls sticky',
  KEN158: 'sugar coated peanuts pile',
  KEN161: 'red chilli hot sauce',
  KEN162: 'creamy chilli coconut sauce',
  KEN163: 'dark tamarind dipping sauce',
  KEN165: 'mango chutney in jar',
  KEN166: 'avocado salsa diced bowl',
  KEN169: 'green chilli relish bowl',
  KEN172: 'goat meat roasting over fire',
  KEN175: 'thin goat meat soup',
  KEN176: [null, 'Camel meat looks identical to beef once stewed and stock libraries hold no camel dishes, so every candidate image would be a stand-in for a different animal.'],
  KEN177: [null, 'Camel milk is the entire identity of this porridge and is invisible in a photo, so any milk-porridge shot would claim something it cannot show.'],
  KEN178: 'sweet potato stew pot',
  KEN179: 'cooked bananas thick sauce',
  KEN180: 'whole fish soup broth',
  KEN182: [null, 'Built on ash-cured fermented milk, which no photograph can distinguish from ordinary milk porridge.'],
  KEN183: 'thick millet porridge mug',
  KEN184: 'brown bean stew bowl',
  KEN186: 'fish stew tamarind broth',
  KEN187: 'coconut chicken stew bowl',
  KEN188: 'river fish curry plate',
  KEN190: 'honey glazed roasted meat',
  KEN191: 'sweet millet porridge honey',
  KEN193: 'peanut porridge creamy bowl',
  KEN194: 'mashed sweet potato breakfast',
  KEN195: 'rice porridge coconut milk',
  KEN196: 'banana porridge mashed bowl',
  KEN198: 'taro chunks breakfast bowl',
  KEN199: 'cassava porridge white bowl',
  KEN201: 'festive pilau rice platter',
  KEN202: 'roast goat leg platter',
  KEN203: 'pilau with beef chunks',
  KEN204: 'biryani platter garnished almonds',
  KEN205: 'baked fish coconut sauce',
  KEN208: 'green mashed potato mound',
  KEN209: 'whole goat roasting spit',
  KEN210: 'nyama choma platter sliced meat',
  KEN214: 'glazed whole fish baked',
  KEN215: 'honey roast whole chicken',
  KEN218: 'coconut dessert in glasses',
  KEN219: 'bean stew large pot',
  KEN220: [null, 'A mixed feast platter has no fixed contents, so the only matching photo would be a generic national-spread shot that misstates what is served.'],
  KEN222: 'beef burger fries plate',
  KEN225: 'spiced masala fries tray',
  KEN226: 'loaded fries cheese sauce',
  KEN227: 'pizza slice melted cheese',
  KEN228: 'grilled chicken panini sandwich',
  KEN229: 'avocado toast sliced bread',
  KEN235: 'coffee cake slice crumb',
  KEN241: 'coffee milkshake tall glass',
  KEN244: 'mango mint iced drink',
  KEN249: 'iced coffee glass milk',
  KEN250: 'mocha coffee cream mug',
  KEN251: 'mixed grill meat platter',
  KEN254: 'pepper steak black sauce',
  KEN262: 'chicken lasagna baked slice',
  KEN271: 'barbecue beef ribs plate',
  KEN278: 'buttered mixed vegetables bowl',
  KEN284: 'three cheesecake slices plate',
  KEN294: 'pancakes drizzled with honey',
  KEN296: 'full breakfast eggs sausage',
  KEN297: 'continental breakfast bread fruit',
  KEN298: 'fruit yogurt granola bowl',
  KEN300: [null, 'A house signature platter is defined by the restaurant that assembles it, so no stock photo can show this particular combination honestly.'],
  KEN301: 'roasted maize cob charcoal',

  // ─── TANZANIA ───────────────────────────────────────────────
  TZA001: 'ugali stiff maize block plate',
  TZA002: 'coconut rice plate garnish',
  TZA004: 'chapati flatbread stack',
  TZA006: 'mandazi coconut doughnut pieces',
  TZA010: 'boiled cassava wedges bowl',
  TZA011: 'cassava coconut sauce bowl',
  TZA012: 'steamed sweet potato halves',
  TZA014: 'millet porridge enamel cup',
  TZA015: 'sorghum porridge bowl',
  TZA016: 'maize meal porridge bowl',
  TZA017: 'white rice meat stew plate',
  TZA018: 'rice and beans plate',
  TZA021: 'grilled beef chunks charcoal',
  TZA022: 'beef stew rich brown gravy',
  TZA023: 'beef pilau rice cloves cardamom',
  TZA024: 'goat stew coconut gravy',
  TZA025: 'goat pilau cloves cinnamon rice',
  TZA026: 'chicken curry tomato sauce',
  TZA027: 'grilled chicken coconut marinade',
  TZA029: 'beef skewers over grill',
  TZA030: 'chicken skewers charcoal grill',
  TZA031: 'beef wet fry onions tomatoes',
  TZA033: 'tripe stew bowl',
  TZA034: 'beef bone soup clear broth',
  TZA035: 'roast goat leg spices',
  TZA036: 'lamb stew thick gravy',
  TZA037: 'lamb pilau rice spices',
  TZA038: 'grilled chicken halves charcoal',
  TZA042: 'beef coconut curry pot',
  TZA043: 'dry fried goat chunks pan',
  TZA044: 'chicken coconut soup bowl',
  TZA045: 'dry fried goat cubes',
  TZA046: 'beef potato stew pot',
  TZA047: 'chicken potato stew pot',
  TZA048: 'goat coconut curry plate',
  TZA049: 'beef peanut stew bowl',
  TZA050: 'spiced chicken wings platter',
  TZA051: 'clear goat meat soup',
  TZA052: 'chicken biryani layered rice',
  TZA054: 'minced beef keema peas',
  TZA056: 'chicken pilau browned rice',
  TZA057: 'mixed meat stew casserole',
  TZA058: 'chicken creamy coconut sauce',
  TZA059: 'beef stir fry peppers',
  TZA060: 'lamb chops charcoal grill',
  TZA061: 'fish basted coconut grilling',
  TZA062: 'fish coconut curry bowl',
  TZA063: 'grilled whole tilapia',
  TZA064: 'fish curry tomato gravy',
  TZA066: 'prawn curry bowl',
  TZA067: 'prawns coconut sauce skillet',
  TZA070: 'mixed seafood platter lime',
  TZA071: 'fish tamarind glaze plate',
  TZA075: 'smoked fish on rack',
  TZA076: 'fried fish balls plate',
  TZA079: 'grilled squid rings lemon',
  TZA080: 'clear fish soup bowl',
  TZA081: 'squid coconut sauce bowl',
  TZA082: 'grilled whole sea bass',
  TZA083: 'creamy coconut fish soup',
  TZA084: 'prawn pilau spiced rice',
  TZA085: 'grilled kingfish steak',
  TZA086: 'fish tamarind stew bowl',
  TZA087: 'prawn mango salad',
  TZA088: 'crab in coconut curry',
  TZA089: 'small dried sardines stew',
  TZA090: 'whole fried crispy fish',
  TZA091: 'kidney beans creamy coconut pot',
  TZA092: 'bean stew tomato pot',
  TZA093: 'pounded cassava leaves stew',
  TZA094: 'amaranth greens coconut pot',
  TZA096: 'sweet potato leaves cooked',
  TZA098: 'sliced okra stew pot',
  TZA100: 'pumpkin leaves stew',
  TZA102: 'yellow lentil curry dal',
  TZA104: 'pigeon peas stew bowl',
  TZA106: 'collard greens sauteed onion',
  TZA107: 'pumpkin stew chunks pot',
  TZA110: 'chickpea curry bowl',
  TZA113: 'lentils coconut milk curry',
  TZA114: 'carrot and pea curry',
  TZA115: 'beans green banana stew',
  TZA117: 'red chili sauce bowl',
  TZA119: 'diced avocado salsa bowl',
  TZA120: 'mixed vegetable coconut stew',
  TZA121: 'biryani rice saffron cardamom',
  TZA124: [null, 'The Zanzibar mix plate is an assembled street bowl of soup, crisps, fritters and chutneys that varies by vendor, so any single stock shot would misrepresent it.'],
  TZA125: 'marinated beef kebabs charcoal',
  TZA126: 'round rice coconut cakes',
  TZA127: 'coconut candy pieces',
  TZA128: 'round flatbread loaf oven',
  TZA130: 'potato coconut curry',
  TZA131: 'pigeon peas coconut milk',
  TZA134: 'fish curry coconut coriander',
  TZA135: 'layered flatbread with coconut',
  TZA136: 'octopus salad lime onion',
  TZA137: 'spiced beef broth bowl',
  TZA139: 'rice pudding coconut cinnamon',
  TZA143: 'tamarind drink glass ice',
  TZA144: 'spiced milk tea glass',
  TZA145: 'fish stew cassava pieces',
  TZA147: 'halwa sticky sweet squares',
  TZA148: 'rice cooked in coconut milk',
  TZA149: 'fried samosa triangles',
  TZA152: 'spiced lamb shoulder roast',
  TZA153: 'sugarcane juice tall glass',
  TZA155: 'roasted cassava sticks charcoal',
  TZA157: 'chicken over rice platter',
  TZA159: 'boiled eggs curry sauce',
  TZA161: 'peanut stew thick sauce',
  TZA165: 'lamb biryani rice platter',
  TZA166: 'chili prawns red sauce',
  TZA167: 'coconut mandazi doughnuts',
  TZA169: 'fish fillet tamarind sauce',
  TZA170: [null, 'A festive multi-dish occasion rather than one dish, so no single photograph could show what a reader would be served.'],
  TZA171: 'french fries omelette skillet',
  TZA172: 'meat skewers street grill',
  TZA174: 'fried cassava chips',
  TZA175: 'battered potato fritters bhajia',
  TZA176: 'samosas on vendor tray',
  TZA177: 'roasted groundnuts paper cone',
  TZA180: 'fries tossed masala sauce',
  TZA181: 'grilled plantain halves',
  TZA182: 'ugali with grilled meat',
  TZA183: 'boiled peanuts bowl',
  TZA184: 'grilled sweet potato slices',
  TZA188: 'deep fried chicken pieces',
  TZA189: 'grilled bananas charcoal',
  TZA191: [null, 'A dry roasted maize flour snack looks like plain pale powder and no stock photo of it would read as food to a reader.'],
  TZA195: 'banana fritters golden fried',
  TZA197: 'sliced mango on stick',
  TZA199: 'peanut brittle slabs',
  TZA200: [null, 'A street food festival is an event, not a dish, and any photo would show a crowd rather than what the recipe makes.'],
  TZA201: 'shredded coconut sweet balls',
  TZA203: 'translucent halwa dessert slices',
  TZA204: 'creamy rice pudding bowl',
  TZA205: 'coconut cake slice',
  TZA206: 'banana fritters powdered sugar',
  TZA207: 'sugared fried dough pieces',
  TZA209: 'tamarind candy balls',
  TZA210: 'tropical fruit salad bowl',
  TZA214: 'sweet maize porridge cup',
  TZA216: 'mango sorbet scoops',
  TZA217: 'cassava pudding slice',
  TZA220: [null, 'A dessert platter is a cook-chosen assortment, so any photo would assert a specific combination this recipe does not fix.'],
  TZA222: 'chai cardamom ginger cup',
  TZA223: 'tamarind juice pitcher',
  TZA224: [null, 'Baobab juice is not in stock libraries and any pale fruit drink photo would simply be a different drink.'],
  TZA225: 'sugarcane press fresh juice',
  TZA228: 'green coconut water machete',
  TZA230: 'hibiscus iced tea glass',
  TZA231: 'avocado smoothie glass',
  TZA240: [null, 'A drinks platter is an arrangement rather than a recipe, so no single photo could honestly stand for it.'],
  TZA244: 'millet ugali dark stiff porridge',
  TZA245: 'plantain stew in pot',
  TZA246: 'sorghum porridge clay bowl',
  TZA247: 'beef potatoes carrots stewed',
  TZA248: 'cassava and beans stew',
  TZA249: 'fish simmered coconut broth',
  TZA250: 'mutton broth with herbs',
  TZA251: 'sorghum peanut paste bowl',
  TZA252: 'mixed garden vegetable stew',
  TZA253: [null, 'Fermented milk porridge is defined by the souring process and looks like plain pale gruel, so no stock photo could identify it.'],
  TZA254: [null, 'This describes a hunter-gatherer foraged meal rather than a plated dish, and any photo would be a staged invention.'],
  TZA255: [null, 'Fermented milk kept in a gourd is identified by its vessel and process, not by an appearance any stock photo captures.'],
  TZA256: 'roasted corn cob charcoal',
  TZA258: 'cassava flour flatbread',
  TZA260: [null, 'These are wild foraged greens with no fixed species or plated form, so a generic cooked-greens photo would name the wrong plant.'],
  TZA263: [null, 'Fermented cassava is a processing step producing an unremarkable pale mash that no honest stock photo exists for.'],
  TZA268: [null, 'Honey gathering is a foraging practice rather than a dish, so there is nothing on a plate to photograph.'],
  TZA269: 'peanut porridge bowl',
  TZA271: [null, 'This ceremonial blood and milk drink is not photographed in stock libraries and no substitute image would be truthful.'],
  TZA273: 'porridge with milk poured',
  TZA275: 'freshwater fish soup bowl',
  TZA276: 'orange sweet potato mash',
  TZA277: [null, 'A milk and millet drink looks like plain pale liquid in a cup, which no photo could distinguish from any other milk drink.'],
  TZA278: [null, 'This is a comparison across regional versions rather than one dish, so a single photo would misstate which one the reader sees.'],
  TZA280: [null, 'A tribal food map is reference content, not a dish, and has no plated form to photograph.'],
  TZA281: 'avocado toast sourdough slice',
  TZA283: 'seafood linguine pasta',
  TZA286: 'glazed grilled fish fillet',
  TZA287: 'prawn curry rice bowl',
  TZA289: 'lamb chops herb marinade',
  TZA291: 'cheesecake slice dark plate',
  TZA293: 'beef tenderloin medallions plated',
  TZA295: 'mezze sharing plates dips',
  TZA297: 'breakfast platter eggs fruit',
  TZA299: [null, 'A signature house platter is a specific assembled plate unique to this kitchen, so any stock photo would show someone else\'s food.'],
  TZA300: [null, 'This is an editorial overview of a cuisine rather than a recipe, so no single dish photo could represent it.'],

  // ─── SOMALIA (the remaining shared-photo ids) ───────────────
  SOM001: 'somali spongy sour flatbread',
  SOM002: 'layered flaky flatbread squares',
  SOM003: 'thin sweet pancake stack honey',
  SOM004: 'round corn flatbread baked',
  SOM005: 'spiced rice raisins carrots platter',
  SOM007: 'clear meat vegetable broth bowl',
  SOM008: 'sambusa pastry triangles plate',
  SOM010: 'bean flour fritters fried bowl',
  SOM011: 'green coriander chilli hot sauce',
  SOM012: 'cardamom milk tea glass',
  SOM013: 'chicken coconut yogurt stew',
  SOM014: 'dried meat cubes in ghee jar',
  SOM015: 'adzuki beans butter sugar bowl',
  SOM016: 'fried dough diamonds sugared',
  SOM017: 'braised goat meat onions pot',
  SOM018: 'spaghetti with banana on plate',
  SOM019: 'half moon filled fried pastry',
  SOM020: 'chopped tomato cucumber onion lime salad',

  // ─── legacy seed recipe (numeric id, 21-field schema) ───────
  2: 'truffle carbonara shaved black truffle',
};

module.exports = QUERIES;
